# Generated by Django 4.2.1 on 2023-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0002_mqtt_timestamp_alter_mqtt_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt',
            name='huminity',
        ),
        migrations.RemoveField(
            model_name='mqtt',
            name='timestamp',
        ),
    ]
