# Generated by Django 4.2.1 on 2023-06-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0004_mqtt_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt',
            name='datetime',
        ),
    ]
