# Generated by Django 4.2.1 on 2023-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0005_remove_mqtt_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
