# Generated by Django 4.2.1 on 2023-06-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0007_alter_mqtt_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
