# Generated by Django 4.2.1 on 2023-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0008_mqtt_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
