# Generated by Django 4.2.1 on 2023-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0009_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signalOn', models.CharField(max_length=255)),
                ('signalOff', models.CharField(max_length=255)),
            ],
        ),
    ]
