# Generated by Django 4.2.1 on 2023-07-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_django_testing', '0010_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_status', models.CharField(max_length=255)),
                ('auto_higher', models.DecimalField(decimal_places=2, max_digits=5)),
                ('auto_lower', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
